[project]
name = "flask-dict-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask>=2.2.5",
    "flask-cors>=6.0.2",
]

[dependency-groups]
dev = [
    "pyinstaller>=6.17.0",
]
